[package]
name = "colstodian"
version = "0.1.0-alpha.2"
authors = ["Gray Olson <gray@grayolson.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
edition = "2018"
description = "An opinionated, practical color management library for games and graphics."
documentation = "https://docs.rs/colstodian"
homepage = "https://github.com/termhn/colstodian"
repository = "https://github.com/termhn/colstodian"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/state/manifest.html

[dependencies]
# kolor = { version = "^0.1.4", default-features = false, features = ["f32", "color-matrices"] }
# kolor = { version = "^0.1.4", default-features = false, features = ["f32", "color-matrices"], path = "../kolor/build/kolor" }
kolor = { version = "^0.1.4", default-features = false, features = ["f32", "color-matrices"], git = "https://github.com/termhn/kolor", branch = "main" }
thiserror = "1.0"
derivative = "2.2"
serde = { version = "1", optional = true, features = ["derive"] }
bytemuck = { version = "1.5.1", optional = true, features = ["derive"] }

[features]
default = ["with-serde", "std", "bytemuck"]
with-serde = ["serde", "kolor/serde1"]
std = ["kolor/std"]
libm = ["kolor/libm"]
