[package]
name = "colstodian"
version = "0.1.0-alpha1"
authors = ["Gray Olson <gray@grayolson.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/state/manifest.html

[dependencies]
kolor = { version = "0.1", default-features = false, features = ["f32", "color-matrices"] }
thiserror = "1.0"
derivative = "2.2"
serde = { version = "1", optional = true, features = ["derive"] }

[features]
default = ["with-serde", "std"]
with-serde = ["serde", "kolor/serde1"]
std = ["kolor/std"]
libm = ["kolor/libm"]
