[package]
name = "colstodian"
version = "0.1.0-alpha.2"
authors = ["Gray Olson <gray@grayolson.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
edition = "2018"
description = "An opinionated, practical color management library for games and graphics."
documentation = "https://docs.rs/colstodian"
homepage = "https://github.com/termhn/colstodian"
repository = "https://github.com/termhn/colstodian"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/state/manifest.html

[dependencies]
# kolor = { version = "^0.1.4", default-features = false, features = ["f32", "color-matrices"] }
# kolor = { version = "^0.1.4", default-features = false, features = ["f32", "color-matrices"], path = "../kolor/build/kolor" }
kolor = { version = "^0.1.4", default-features = false, features = ["f32", "color-matrices"], git = "https://github.com/termhn/kolor", rev = "90c2f32" }
glam = { version = "0.13.1", default-features = false } # keep in sync with kolor
thiserror = "1.0"
derivative = "2.2"
serde = { version = "1", optional = true, features = ["derive"] }
bytemuck = { version = "1.5.1", optional = true, features = ["derive"] }

[features]
default = ["std"]

# enable support for the standard library
std = ["kolor/std", "glam/std"]

# libm is required when building with no_std
libm = ["kolor/libm", "glam/libm"]

# add serde Serialize/Deserialize to relevant types
with-serde = ["serde", "kolor/serde1", "glam/serde"]

# add relevant bytemuck trait implementations
with-bytemuck = ["bytemuck", "glam/bytemuck"]
